version: "3.3"

services:
  app:
    restart: always
    build: .
    command: flask run --host 0.0.0.0 --port 5051
    tty: true
    volumes:
      - .:/var/www/mycv2
    ports:
      - 5051:5051
    depends_on:
      - db
    env_file:
      - .env
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development

  db:
    restart: always
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: docker_mysqlcv2
    ports:
      - 3360:3360
    volumes:
      - ./docker/db/data:/var/lib/mysql
    env_file:
      - .env

